// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIyrcHRuFl2a5XVi59CQj7k9hDN_FGABo',
    appId: '1:602867949764:web:5ea7d47500b50786e8e991',
    messagingSenderId: '602867949764',
    projectId: 'notes-f91fa',
    authDomain: 'notes-f91fa.firebaseapp.com',
    storageBucket: 'notes-f91fa.firebasestorage.app',
    measurementId: 'G-WEHWXGT43P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBplKxPb0Sjy-3DVPCjewkrGcR9GxVc_XQ',
    appId: '1:602867949764:android:a96eac04fdc7ffc9e8e991',
    messagingSenderId: '602867949764',
    projectId: 'notes-f91fa',
    storageBucket: 'notes-f91fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMQruS11gAQw5pUUHLjhSSJAc3o7hNVxw',
    appId: '1:602867949764:ios:528eb89cc47edf65e8e991',
    messagingSenderId: '602867949764',
    projectId: 'notes-f91fa',
    storageBucket: 'notes-f91fa.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudnote',
  );
}
